- id: tartufo
  name: Tartufo
  description: '`tartufo` is a tool for scanning git repositories for secrets/passwords/high-entropy data'
  entry: tartufo pre-commit
  language: python
  args: [--regex]
  pass_filenames: false
