[tool.tartufo]
  repo-path = "."
  json = false
  regex = true
  entropy = true
  exclude-entropy-patterns = [
    { path-pattern = 'src/.*$', pattern = '[\+-]{2} [ab]/.+', reason = 'file path in git patch format, excluding first char "+/-"' },
    { path-pattern = 'src/.*$', pattern = 'iff --git ', reason = 'file path mentioned in git diff format, excluding first char of "diff"' },
    { path-pattern = 'src/.*$', pattern = 'ename (from|to) ', reason = 'renamed file path mentioned in git commit, excluding first char of "rename"' },
    { path-pattern = '\.github/workflows/.*\.yml$', pattern = 'uses: .*@[a-zA-Z0-9]{40}', reason = 'commit hashes used in GitHub Actions' },
    { path-pattern = '\.github/workflows/.*\.yml$', pattern = 'GITHUB_WORKSPACE\/.*', reason = 'GitHub Actions config' },
    { path-pattern = 'readme.md$', pattern = '49FD46E6C4B45C55D4AC49FD46E6C4B45C55D4AC', reason = 'sample code in readme' },
    { path-pattern = '.*/main/.*/DomainCreateWithExtensionDemo.java', pattern = '49FD46E6C4B45C55D4AC49FD46E6C4B45C55D4AC', reason = 'sample code in readme' },
    { path-pattern = '.*/test/.*\.java$', pattern = '(49FD46E6C4B45C55D4AC|38FD46E6C4B45C55D4AC|39FD46E6C4B45C55D4AC)', reason = 'Hex value of DS data digest used in tests' },
    { path-pattern = 'cpp/.*\.cpp$', pattern = '(49FD46E6C4B45C55D4AC|38FD46E6C4B45C55D4AC|39FD46E6C4B45C55D4AC)', reason = 'Hex value of DS data digest used in tests' },
    { path-pattern = '.*/test/.*\.java$', pattern = 'void should[a-zA-Z]{30,}', reason = 'all unit test method names' },
    { path-pattern = '.*/test/.*\.java$', pattern = '^D604E5509E82DF9F3105B7E182BB4DF28', scope = 'word', reason = 'a ROID literal used in tests' },
    { path-pattern = 'cpp/se/DomainInfoKVResponseExtensionTest.cpp', pattern = '^D604E5509E82DF9F3105B7E182BB4DF28', scope = 'word', reason = 'a ROID literal' },
    { path-pattern = 'src/test/.*/PollResponseTest.java$', pattern = '^[A-Za-z0-9+/]{30,}$', scope = 'word', reason = 'ROID, DNSSEC pubKey from a PollResponseTest' },
    { path-pattern = 'src/test/.*/Tm.*Test.java$', pattern = '^[A-Za-z0-9+/=]{44,}$', scope = 'word', reason = 'SMD literal from TmchXMLUtilIntegrationTest and TmchValidatingParserTest' },
    { path-pattern = 'src/test/.*/MarkAbstractTest.java$', pattern = '^[A-Za-z0-9+/=]{44,}$', scope = 'word', reason = 'SMD literal from MarkAbstractTest' },
    { path-pattern = '.*/test/.*/PerfTest.java$', pattern = '1207098411691033136503880218', reason = 'client transaction ID in test' },
    { path-pattern = 'src/test/.*/Domain.*ExtensionTest.java$', pattern = 'ACF7B10EBC3284E34B4A7C350DA27EA7B', reason = 'application ID in test' },
    { path-pattern = 'src/test/.*/Tm.*Test.java$', pattern = '370d0b7c9223372036854775807', reason = 'tmNotice ID in TmdbClientComponentTest and TmNoticeXmlParserTest' },
    { path-pattern = 'src/test/component/resources/sample-tmNotice.xml', pattern = '370d0b7c9223372036854775807', reason = 'tmNotice ID in XML file used by test' },
    { path-pattern = 'src/main/resources/xmldsig-core-schema.xsd', pattern = 'http://www.w3.org/Consortium/Legal/', reason = 'URL from www.w3.org' },
  ]
  exclude-path-patterns = [
    { path-pattern = 'tartufo.toml', reason = 'tartufo config itself' },
    { path-pattern = 'Pipfile.lock', reason = 'Pipfile lock as there are many git hash' },
    { path-pattern = 'src/test/.*.smd', reason = 'SMD file used in various tests' },
    { path-pattern = 'src/test/integration/resources/tmch.cr[lt]', reason = 'CRL or CRT file used in integration test' },
    { path-pattern = 'src/test/integration/resources/.*S(MD|md).*.txt', reason = 'SMD file used in integration test' },
    { path-pattern = 'docs/javadoc/.*.html', reason = 'JavaDoc files that no longer exist' },
    { path-pattern = 'gradle/wrapper/gradle-wrapper.properties', reason = 'Auto-downloaded Gradle wrapper file' },
    # A justification is REQUIRED, when a new file needs to be excluded in this section
  ]
  exclude-signatures = [
  ]
