# This GitHub workflow will be invoked in below scenarios:
#
# Trigger the build on push or pull request, only for
# the default branch.
#
# When there is a push to the default branch (could be
# a result of PR merge), a release will be published to
# GitHub Packages (GPR).
#
# This workflow uses actions that are certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#

name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:

  tartufo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo to be Scanned
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # @v3.1.0
      - name: Tartufo Scan
        uses: godaddy/tartufo-action@3d4684c758fa9fdaf9b9cb044d0b9daa86606525  # @v3.2.1

  build:
    needs:
      - tartufo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # @v3.1.0
      - name: Set up JDK 8
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d  # @v3.5.1
        with:
          java-version: '8.0.282'  # required for a few tests
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1  # post @v1.0.4
      - name: Cache Gradle packages
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7  # @v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build

  publish-snapshot:
    if: github.event.pull_request.head.repo.full_name == github.repository
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # @v3.1.0
      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d  # @v3.5.1
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1  # post @v1.0.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Change version from 'major.minor.patch' to 'major.minor-SNAPSHOT'
        run: |
          sed -i -E 's/([0-9]+).([0-9]+).([0-9]+)$/\1.\2-SNAPSHOT/' $GITHUB_WORKSPACE/gradle.properties
      - name: Publish package
        run: |
          ./gradlew -DrepoUrl="$GPR_URL" \
                    -DrepoUsername="$GPR_USER" \
                    -DrepoPassword="$GPR_TOKEN" publish
        env:
          GPR_URL: "https://maven.pkg.github.com/${{ github.repository }}"
          GPR_USER: "${{ env.GITHUB_ACTOR }}"
          GPR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
