# This GitHub workflow will be invoked in below scenarios:
#
# 1. Publishing a release
#

name: Release with Gradle

on:
  release:
    types: [ published ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # @v3.1.0
      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d  # @v3.5.1
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1  # post @v1.0.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish package
        run: |
          ./gradlew -DrepoUrl="$GPR_URL" \
                    -DrepoUsername="$GPR_USER" \
                    -DrepoPassword="$GPR_TOKEN" publish
        env:
          GPR_URL: "https://maven.pkg.github.com/${{ github.repository }}"
          GPR_USER: "${{ env.GITHUB_ACTOR }}"
          GPR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
