# Execute tartufo checks on the git repository.
#
# Only activate this GHA for GHEC, as it requires additional
# configuration for the tartufo action.
#

name: Tartufo Check

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:

  tartufo:
    if: github.repository_owner == 'gdcorp-registry'
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials for ECR access
      uses: aws-actions/configure-aws-credentials@a17646e2633d1f79886a1530ccce16c95a3bb8dc
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}         # AccessKeyId from AWS Secrets Manager
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # SecretAccessKey from AWS Secrets Manager
        role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}              # AWS role ARN of Deploy user
        role-duration-seconds: 1200                                 # default max is 7200
        aws-region: us-west-2                                       # set region you want to target

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@41032bd0f8164c350fb597a5e1ec886624de7465

    - name: Docker login for Golden Containers ECR
      env:
        ECR_REGISTRY: 764525110978.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com # Do NOT change (region pulled from above)!
      run: |
        echo "Using: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Checkout Current Repo to be Scanned
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Checkout Tartufo Repo
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        repository: gdcorp-actions/tartufo
        token: ${{ secrets.GPR_USER_TOKEN }} # PAT with read access to gdcorp-actions/tartufo
        path: tartufo
        ref: main
        persist-credentials: false # Do not persist auth token in local git config.

    - name: Tartufo secret scanning using the Tartufo GitHub Action
      uses: ./tartufo
      with:
        github_token: ${{ secrets.GPR_USER_TOKEN }}
